# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/sk/Common/comp3211/proj/proj.runs/synth_1/single_cycle_core.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/sk/Common/comp3211/proj/proj.cache/wt [current_project]
set_property parent.project_path /media/sk/Common/comp3211/proj/proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo /media/sk/Common/comp3211/proj/proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/EXMEM_reg.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/IDEX_reg.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/IFID_reg.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/MEMWB_reg.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/adder_16b.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/adder_4b.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/control_unit.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/data_memory.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/forwarding_unit.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/hazard_unit.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/instruction_memory.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/mux_2to1_16b.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/mux_2to1_1b.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/new/mux_2to1_5b.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/program_counter.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/register_file.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/sign_extend_4to16.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/single_register.vhd
  /media/sk/Common/comp3211/proj/proj.srcs/sources_1/imports/sources_1/single_cycle_core.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/sk/Common/comp3211/proj/proj.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files /media/sk/Common/comp3211/proj/proj.srcs/constrs_1/imports/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /media/sk/Common/comp3211/proj/proj.srcs/utils_1/imports/synth_1/single_cycle_core.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top single_cycle_core -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef single_cycle_core.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file single_cycle_core_utilization_synth.rpt -pb single_cycle_core_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
